### ISSUE TITLE
allow running apimonitor from arbitrary directory

### ISSUE THREAD

**Issue by dweinstein** [kelwin/apkil#2]
running apimonitor from outside the apkil directory causes issues. simplest example error would be [error] Config file not found: config/default_api_collection because the default is a relative path.

I took a stab at trying to fix the issue but it turned out to be more than just a simple patch as it looks like it would require some changes in apkil/monitor.py as well. Should think about how to handle paths so that it isn't so sensitive to where apimonitor is being run.

**Comment by kelwin** [comment]
Thanks for your advice:) I'll fix it.

**Comment by kelwin** [comment]
I've fixed the issue
