### ISSUE TITLE
issue with picking up output dir option

### ISSUE THREAD

**Issue by tworangez** [kelwin/apkil#3]
$ ./apimonitor.py /tmp/a.apk -o /tmp/

Traceback (most recent call last):
  File "./apimonitor.py", line 67, in <module>
    new_apk = os.path.join(outdir, root_name + "_new.apk")
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'list' object has no attribute 'endswith'

suggest change "args.output" at line58, apimonitor.py to "args.output[0]"

**Comment by kelwin** [comment]
Fixed.Thanks:)
